(() => {
  const request = async (url, options = {}) => { const response = await fetch(url, { credentials:'same-origin', headers:{'Content-Type':'application/json', ...(options.headers || {})}, ...options }); const data = response.status === 204 ? null : await response.json().catch(() => ({})); if (!response.ok) throw new Error(data?.error || 'Não foi possível concluir a solicitação.'); return data; };
  const imageData = (file) => new Promise((resolve, reject) => { if (!file) return resolve(null); if (file.size > 2_000_000) return reject(new Error('A imagem deve ter no máximo 2 MB.')); const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = () => reject(new Error('Não foi possível ler a imagem.')); reader.readAsDataURL(file); });
  const esc = (value = '') => String(value).replace(/[&<>'"]/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  document.addEventListener('DOMContentLoaded', async () => {
    let user; try { user = (await TechCycleAuth.session()).user; document.querySelector('[data-user-name]').textContent = user.username; } catch (_) { return location.replace('/login'); }
    document.querySelector('[data-logout]').addEventListener('click', async () => { await TechCycleAuth.logout(); location.assign('/login'); });
    if (user.role !== 'admin') {
      const history = document.createElement('section'); history.className = 'my-reports'; history.innerHTML = '<h2>Minhas denúncias</h2><div id="my-reports-list"><p class="muted-text">Carregando...</p></div>'; document.querySelector('#member-report').after(history);
      try {
        const { reports } = await request('/api/my-reports');
        const labels = { received:'Recebida', in_review:'Em análise', resolved:'Resolvida', closed:'Encerrada' };
        history.querySelector('#my-reports-list').innerHTML = reports.length ? reports.map((report) => `<article class="report-card"><div class="report-head"><strong>Denúncia #${report.id}</strong><span class="report-status">${labels[report.status] || report.status}</span></div><p>${esc(report.description)}</p><small>Enviada em ${new Date(report.created_at).toLocaleDateString('pt-BR')}</small>${report.admin_message ? `<div class="admin-reply"><strong>Resposta da administração</strong><p>${esc(report.admin_message)}</p></div>` : '<p class="muted-text">A administração ainda não respondeu.</p>'}</article>`).join('') : '<p class="muted-text">Você ainda não enviou nenhuma denúncia.</p>';
      } catch (error) { history.querySelector('#my-reports-list').innerHTML = `<p class="message">${esc(error.message)}</p>`; }
    }
    if (user.role !== 'admin') {
      const form = document.querySelector('#report-form'), message = form.querySelector('[data-report-message]');
      form.addEventListener('submit', async (event) => { event.preventDefault(); if (!form.checkValidity()) return form.reportValidity(); const data = new FormData(form); try { const payload = { address:data.get('address'), cep:data.get('cep'), contact:data.get('contact'), description:data.get('description'), isAnonymous:data.get('isAnonymous') === 'on', imageData:await imageData(data.get('image')) }; await request('/api/reports', { method:'POST', body:JSON.stringify(payload) }); form.reset(); message.textContent = 'Denúncia enviada com segurança para análise.'; } catch (error) { message.textContent = error.message; } }); return;
    }
    document.querySelector('#member-report').hidden = true; document.querySelector('#admin-reports').hidden = false; document.querySelector('#reports-subtitle').textContent = 'Analise as denúncias recebidas e responda aos membros.';
    const list = document.querySelector('#reports-list'); try { const { reports } = await request('/api/reports'); list.innerHTML = reports.length ? reports.map((report) => `<article class="report-card admin-report"><div class="report-head"><strong>Denúncia #${report.id}</strong><small>${new Date(report.created_at).toLocaleString('pt-BR')}</small></div><p><b>Autor:</b> ${report.author_name ? esc(report.author_name) : 'Anônimo'}</p><p><b>Local:</b> ${esc(report.address)} — ${esc(report.cep)}</p><p><b>Contato:</b> ${esc(report.contact)}</p><p>${esc(report.description)}</p>${report.image_data ? `<img class="report-image" src="${report.image_data}" alt="Imagem da denúncia">` : ''}<label class="field">Status<select data-status="${report.id}"><option value="received" ${report.status==='received'?'selected':''}>Recebida</option><option value="in_review" ${report.status==='in_review'?'selected':''}>Em análise</option><option value="resolved" ${report.status==='resolved'?'selected':''}>Resolvida</option><option value="closed" ${report.status==='closed'?'selected':''}>Encerrada</option></select></label><label class="field">Resposta ou pergunta<textarea data-message="${report.id}" rows="3" placeholder="Escreva uma resposta ao denunciante">${esc(report.admin_message || '')}</textarea></label><button class="button" data-save="${report.id}" type="button">Salvar atualização</button></article>`).join('') : '<section class="empty-card">Nenhuma denúncia recebida.</section>'; list.querySelectorAll('[data-save]').forEach((button) => button.addEventListener('click', async () => { const id=button.dataset.save; try { await request(`/api/reports/${id}`, { method:'PUT', body:JSON.stringify({ status:list.querySelector(`[data-status="${id}"]`).value, adminMessage:list.querySelector(`[data-message="${id}"]`).value }) }); button.textContent='Atualizado'; } catch(error) { button.textContent=error.message; } })); } catch (error) { list.innerHTML = `<p class="message">${esc(error.message)}</p>`; }
  });
})();
