(() => {
  const esc = (value = '') => String(value).replace(/[&<>'"]/g, (char) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[char]));
  const request = async (url, options = {}) => { const response = await fetch(url, { credentials:'same-origin', headers:{ 'Content-Type':'application/json', ...(options.headers || {}) }, ...options }); const data = response.status === 204 ? null : await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Não foi possível concluir a solicitação.'); return data; };
  const id = location.pathname.split('/').pop(), detail = document.querySelector('#idea-detail'), commentsEl = document.querySelector('#comments-list'), notice = document.querySelector('#idea-message'); let user = null;
  const avatar = (image, name) => `<span class="avatar">${image ? `<img src="${image}" alt="Foto de ${esc(name)}">` : esc(name).slice(0,2).toUpperCase()}</span>`;
  const stars = () => [1,2,3,4,5].map((rating) => `<button class="star" data-rating="${rating}" aria-label="Avaliar com ${rating} estrelas">★</button>`).join('');
  function modal({ title, text, value = '', confirmLabel = 'Confirmar', danger = false }) { return new Promise((resolve) => { const element = document.createElement('div'); element.className = 'modal-backdrop'; element.innerHTML = `<section class="modal-card" role="dialog" aria-modal="true" aria-labelledby="modal-title"><h2 id="modal-title">${esc(title)}</h2><p>${esc(text)}</p>${value !== null ? `<textarea maxlength="1500">${esc(value)}</textarea>` : ''}<div class="modal-actions"><button class="button modal-cancel" type="button">Cancelar</button><button class="button ${danger ? 'modal-danger':''}" type="button">${esc(confirmLabel)}</button></div></section>`; document.body.append(element); const textarea = element.querySelector('textarea'); textarea?.focus(); const close = (result) => { element.remove(); resolve(result); }; element.querySelector('.modal-cancel').onclick = () => close(null); element.querySelector('.modal-actions .button:last-child').onclick = () => close(textarea ? textarea.value.trim() : true); element.addEventListener('click', (event) => { if (event.target === element) close(null); }); }); }
  const showComments = (comments) => { const roots = comments.filter((comment) => !comment.parent_id); const replies = (parent) => comments.filter((comment) => Number(comment.parent_id) === Number(parent)); const single = (comment, child = false) => `<article class="comment ${child ? 'reply':''}"><div class="post-meta">${avatar(comment.author_profile_image, comment.author_name)}<div><strong>${esc(comment.author_name)}</strong><div class="comment-meta">${new Date(comment.created_at).toLocaleDateString('pt-BR')}</div></div></div><p>${esc(comment.content)}</p><div class="comment-actions"><button class="text-button" data-reply="${comment.id}">Responder</button>${user && Number(user.id) === Number(comment.author_id) ? `<button class="text-button" data-edit="${comment.id}" data-content="${esc(comment.content)}">Editar</button><button class="text-button" data-delete="${comment.id}">Excluir</button>` : ''}</div>${replies(comment.id).map((reply) => single(reply, true)).join('')}</article>`; commentsEl.innerHTML = roots.map((comment) => single(comment)).join('') || '<p class="section-subtitle">Ainda não há comentários. Comece a conversa.</p>'; };
  async function loadComments() { try { showComments((await request(`/api/ideas/${id}/comments`)).comments); } catch (_) { commentsEl.innerHTML = '<p class="message">Não foi possível carregar os comentários.</p>'; } }
  async function load() { try { const { idea } = await request(`/api/ideas/${id}`); detail.classList.remove('loading-card'); detail.innerHTML = `<div class="post-meta">${avatar(idea.author_profile_image, idea.author_name)}<div><strong>${esc(idea.author_name)}</strong><small>Publicado em ${new Date(idea.created_at).toLocaleDateString('pt-BR')} · ${esc(idea.category_name || '')}</small></div></div><h1 class="detail-title">${esc(idea.title)}</h1><div class="tags">${(idea.tags || []).map((tag) => `<span class="tag">#${esc(tag)}</span>`).join('')}</div>${idea.image_data ? `<img class="idea-image" src="${idea.image_data}" alt="Imagem da ideia: ${esc(idea.title)}">` : ''}<p class="detail-content">${esc(idea.content)}</p><div class="idea-stats"><span class="rating">★ ${Number(idea.average_rating).toFixed(1)} de 5</span><span>${idea.rating_count} avaliações</span><span>${idea.comment_count} comentários</span></div><div class="rating-control"><span>Avalie:</span>${stars()}</div>`; } catch (error) { detail.textContent = error.message; } }
  document.addEventListener('DOMContentLoaded', async () => {
    try { user = (await TechCycleAuth.session()).user; document.querySelectorAll('[data-user-name]').forEach((el) => el.textContent = user.username); const logout = document.querySelector('[data-logout]'); logout.hidden = false; logout.addEventListener('click', async () => { await TechCycleAuth.logout(); location.assign('/login'); }); } catch (_) {}
    await load(); await loadComments();
    detail.addEventListener('click', async (event) => { const button = event.target.closest('[data-rating]'); if (!button) return; if (!user) return location.assign(`/login?next=${encodeURIComponent(location.pathname)}`); try { await request(`/api/ideas/${id}/rating`, { method:'POST', body:JSON.stringify({ rating:Number(button.dataset.rating) }) }); await load(); } catch (error) { notice.textContent = error.message; } });
    document.querySelector('#comment-form').addEventListener('submit', async (event) => { event.preventDefault(); if (!user) return location.assign(`/login?next=${encodeURIComponent(location.pathname)}`); const form = event.currentTarget; try { await request(`/api/ideas/${id}/comments`, { method:'POST', body:JSON.stringify({ content:new FormData(form).get('content') }) }); form.reset(); await loadComments(); await load(); } catch (error) { notice.textContent = error.message; } });
    commentsEl.addEventListener('click', async (event) => { const button = event.target.closest('button'); if (!button) return; if (!user) return location.assign(`/login?next=${encodeURIComponent(location.pathname)}`); try { if (button.dataset.reply) { const content = await modal({ title:'Responder comentário', text:'Sua resposta será publicada na comunidade.', confirmLabel:'Publicar resposta' }); if (content) await request(`/api/ideas/${id}/comments`, { method:'POST', body:JSON.stringify({ content, parentId:Number(button.dataset.reply) }) }); } if (button.dataset.edit) { const content = await modal({ title:'Editar comentário', text:'Atualize sua mensagem.', value:button.dataset.content, confirmLabel:'Salvar alteração' }); if (content) await request(`/api/comments/${button.dataset.edit}`, { method:'PUT', body:JSON.stringify({ content }) }); } if (button.dataset.delete) { const confirmed = await modal({ title:'Excluir comentário?', text:'Esta ação não poderá ser desfeita.', value:null, confirmLabel:'Excluir', danger:true }); if (confirmed) await request(`/api/comments/${button.dataset.delete}`, { method:'DELETE' }); } await loadComments(); await load(); } catch (error) { notice.textContent = error.message; } });
  });
})();
