document.addEventListener('DOMContentLoaded', async () => {
  const target = document.querySelector('#my-ideas'), picker = document.querySelector('#photo-picker'), avatar = document.querySelector('[data-profile-avatar]'), photoMessage = document.querySelector('#photo-message'), saveButton = document.querySelector('#save-profile-photo'); let user, pendingPhoto = null;
  const esc = (value = '') => String(value).replace(/[&<>'"]/g, (char) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[char]));
  const request = async (url, options = {}) => { const response = await fetch(url, { credentials:'same-origin', headers:{ 'Content-Type':'application/json', ...(options.headers || {}) }, ...options }); const data = response.status === 204 ? null : await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Não foi possível concluir a solicitação.'); return data; };
  const paintAvatar = (profileImage, username) => { avatar.innerHTML = profileImage ? `<img src="${profileImage}" alt="Foto de perfil de ${esc(username)}">` : esc(username).slice(0, 2).toUpperCase(); };
  function choosePhoto(payload, preview) { pendingPhoto = payload; paintAvatar(preview, user.username); photoMessage.textContent = 'Foto selecionada. Salve as alterações para publicar a mudança.'; saveButton.hidden = false; }
  async function savePhoto() { if (!pendingPhoto) return; saveButton.disabled = true; photoMessage.textContent = 'Salvando alterações…'; try { const response = await request('/api/me/profile-photo', { method:'PUT', body:JSON.stringify(pendingPhoto) }); user = response.user; pendingPhoto = null; paintAvatar(user.profileImage, user.username); photoMessage.textContent = 'Foto de perfil atualizada para toda a comunidade.'; saveButton.hidden = true; picker.hidden = true; } catch (error) { photoMessage.textContent = error.message; } finally { saveButton.disabled = false; } }
  try { user = (await TechCycleAuth.session()).user; document.querySelectorAll('[data-user-name]').forEach((element) => element.textContent = user.username); paintAvatar(user.profileImage, user.username); const response = await fetch('/api/me/ideas', { credentials:'same-origin' }); const { ideas = [] } = await response.json(); target.innerHTML = ideas.length ? ideas.map((idea) => `<article class="post idea-card"><h2><a href="/ideia/${idea.id}">${esc(idea.title)}</a></h2><div class="idea-stats"><span>★ ${Number(idea.average_rating).toFixed(1)} (${idea.rating_count})</span><span>◌ ${idea.comment_count} comentários</span></div></article>`).join('') : '<section class="empty-card"><p>Você ainda não publicou ideias.</p><a href="/criar-post">Compartilhar uma ideia</a></section>'; const { suggestions } = await request('/api/profile/photo-suggestions'); document.querySelector('#photo-suggestions').innerHTML = suggestions.map((item) => `<button class="photo-option" type="button" data-suggestion="${item.id}" data-image="${item.image_url}"><img src="${item.image_url}" alt="${esc(item.title)}"><span>${esc(item.title)}</span></button>`).join(''); } catch (_) { location.replace('/login'); return; }
  document.querySelector('#open-photo-picker').onclick = () => { picker.hidden = false; photoMessage.textContent = ''; picker.scrollIntoView({ behavior:'smooth', block:'nearest' }); };
  document.querySelector('#close-photo-picker').onclick = () => { picker.hidden = true; if (pendingPhoto) { pendingPhoto = null; paintAvatar(user.profileImage, user.username); saveButton.hidden = true; } };
  document.querySelector('#profile-image-input').addEventListener('change', async (event) => { const file = event.target.files[0]; if (!file) return; if (file.size > 2 * 1024 * 1024) { photoMessage.textContent = 'A imagem deve ter no máximo 2 MB.'; return; } const imageData = await new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file); }); choosePhoto({ imageData }, imageData); });
  document.querySelector('#photo-suggestions').addEventListener('click', (event) => { const button = event.target.closest('[data-suggestion]'); if (button) choosePhoto({ suggestionId:Number(button.dataset.suggestion) }, button.dataset.image); });
  saveButton.onclick = savePhoto;
  document.querySelector('[data-logout]')?.addEventListener('click', async () => { await TechCycleAuth.logout(); location.assign('/login'); });
});
