document.addEventListener('DOMContentLoaded', async () => {
  const request = async (url, options = {}) => { const response = await fetch(url, { credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, ...options }); const data = await response.json().catch(() => ({})); if (!response.ok) throw Error(data.error || 'Não foi possível concluir a solicitação.'); return data; };
  const form = document.querySelector('#tutorial-form'); const upload = document.querySelector('#tutorial-upload'); const message = document.querySelector('[data-form-message]'); const list = document.querySelector('#tutorials-list');
  const read = (file) => new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file); });
  const esc = (value) => String(value || '').replace(/[<>&"]/g, (char) => ({ '<':'&lt;', '>':'&gt;', '&':'&amp;', '"':'&quot;' }[char]));
  list.addEventListener('mouseenter', (event) => { const media = event.target.closest('.tutorial-media'); if (!media || media.querySelector('.tutorial-fullscreen')) return; const button = document.createElement('button'); button.className = 'tutorial-fullscreen'; button.type = 'button'; button.textContent = '⛶'; button.title = 'Tela cheia'; button.addEventListener('click', () => { const video = media.querySelector('video'); if (document.fullscreenElement) document.exitFullscreen(); else (video.requestFullscreen || media.requestFullscreen).call(video.requestFullscreen ? video : media); }); media.append(button); }, true);
  const render = (ideas) => { list.innerHTML = ideas.length ? ideas.map((idea) => { const initials = esc(idea.author_name).slice(0, 2).toUpperCase(); const avatar = idea.author_profile_image ? `<img src="${idea.author_profile_image}" alt="Foto de ${esc(idea.author_name)}">` : initials; return `<article class="post tutorial-card"><div class="tutorial-media"><video class="tutorial-player" src="${idea.video_data}" ${idea.cover_data ? `poster="${idea.cover_data}"` : ''} preload="metadata"></video><button class="tutorial-play" type="button" aria-label="Reproduzir vídeo">▶</button></div><div class="tutorial-info"><h2>${esc(idea.title)}</h2><p>${esc(idea.content)}</p><div class="tutorial-author"><span class="tutorial-avatar">${avatar}</span><span>${esc(idea.author_name)}</span></div><select class="tutorial-speed" aria-label="Velocidade de reprodução"><option value="1">1x</option><option value="1.25">1,25x</option><option value="1.5">1,50x</option><option value="1.75">1,75x</option><option value="2">2x</option></select></div></article>`; }).join('') : '<section class="empty-card"><p>Ainda não há tutoriais publicados.</p></section>'; list.querySelectorAll('.tutorial-card').forEach((card) => { const video = card.querySelector('.tutorial-player'); const play = card.querySelector('.tutorial-play'); const speed = card.querySelector('.tutorial-speed'); const sync = () => { play.textContent = video.paused ? '▶' : '❚❚'; play.setAttribute('aria-label', video.paused ? 'Reproduzir vídeo' : 'Pausar vídeo'); }; play.addEventListener('click', () => { video.paused ? video.play() : video.pause(); }); video.addEventListener('play', sync); video.addEventListener('pause', sync); video.addEventListener('ended', sync); speed.addEventListener('change', () => { video.playbackRate = Number(speed.value); video.defaultPlaybackRate = Number(speed.value); }); }); };
  try { const { user } = await TechCycleAuth.session(); document.querySelectorAll('[data-user-name]').forEach((element) => { element.textContent = user.username; }); const { categories } = await request('/api/categories'); document.querySelector('#tutorial-category').insertAdjacentHTML('beforeend', categories.map((category) => `<option value="${category.id}">${category.name}</option>`).join('')); const { ideas } = await request('/api/ideas?type=tutorial&limit=50&sort=recent'); render(ideas.filter((idea) => idea.video_data)); } catch (_) { location.replace(`/login?next=${encodeURIComponent(location.pathname)}`); return; }
  document.querySelector('#open-tutorial-upload').addEventListener('click', () => { upload.hidden = !upload.hidden; }); document.querySelector('[data-logout]').addEventListener('click', async () => { await TechCycleAuth.logout(); location.assign('/login'); });
  form.addEventListener('submit', async (event) => { event.preventDefault(); const button = form.querySelector('button'); button.disabled = true; message.textContent = ''; try { const data = Object.fromEntries(new FormData(form)); const video = form.querySelector('[name="video"]').files[0]; const cover = form.querySelector('[name="cover"]').files[0]; if (video.size > 128 * 1024 * 1024) throw Error('O vídeo deve ter no máximo 128 MB.'); if (cover.size > 50 * 1024 * 1024) throw Error('A capa deve ter no máximo 50 MB.'); const duration = await new Promise((resolve, reject) => { const element = document.createElement('video'); element.preload = 'metadata'; element.onloadedmetadata = () => { URL.revokeObjectURL(element.src); resolve(element.duration); }; element.onerror = () => reject(Error('Não foi possível ler o vídeo.')); element.src = URL.createObjectURL(video); }); if (duration < 1 || duration > 300) throw Error('O vídeo deve ter entre 1 segundo e 5 minutos.'); data.videoData = await read(video); data.coverData = await read(cover); delete data.video; delete data.cover; data.imageData = null; await request('/api/ideas', { method: 'POST', body: JSON.stringify(data) }); location.reload(); } catch (error) { message.textContent = error.message; button.disabled = false; } });
});
